Bootstrap: debootstrap
OSVersion: buster
MirrorURL: http://ftp.ca.debian.org/debian/

%files


%post
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y curl gnupg2 python3 wget python3-pip git
    apt-get install -y ca-certificates lsb-release apt-transport-https dirmngr
    curl --silent -o apt.gpg https://packages.sury.org/php/apt.gpg
    echo "deb http://cran.rstudio.com/bin/linux/debian stretch-cran35/" >> /etc/apt/sources.list
    apt-key add /apt.gpg
    apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
    apt-get -qqq update
    apt-get -qqq upgrade

    pip3 install biopython


    
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
    dpkg-reconfigure --frontend noninteractive tzdata
    apt-get -y install alien libcurl4-openssl-dev libxml2-dev

    curl -s ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast-2.9.0+-1.x86_64.rpm --output ncbi-blast-2.9.0+-1.x86_64.rpm
    alien -i ncbi-blast-2.9.0+-1.x86_64.rpm

    apt-get update && apt-get install -y && \

    apt-get install -y locales locales-all && \
     export LANGUAGE=en_US.UTF-8 && \
     export LANG=en_US.UTF-8 && \
     export LC_ALL=en_US.UTF-8 && \
     locale-gen en_US.UTF-8 && \
     dpkg-reconfigure locales
    rm ncbi-blast-2.9.0+-1.x86_64.rpm
    rm -r /var/lib/apt/lists/*
